// Generated by CoffeeScript 1.7.1
var assert, express, mongoose, request;

assert = require('assert');

express = require('..');

request = require('supertest');

mongoose = require('mongoose');

describe('Array', function() {
  return describe('#indexOf()', function() {
    return it('should return -1 when the value is not present', function() {
      assert.equal(-1, [1, 2, 3].indexOf(5));
      return assert.equal(-1, [1, 2, 3].indexOf(0));
    });
  });
});

describe('Routing', function() {
  var url;
  url = "http://localhost:4000";
  return describe('Homepage', function() {
    return it("Should return 200 on homepage", function() {
      return request(url).get('/').expect(200);
    });
  });
});
