// Generated by CoffeeScript 1.7.1
var Chat, app, bodyParser, db, express, expressHandlebars, http, io, messageSchema, mongoose, server;

express = require('express');

app = express();

http = require('http').Server(app);

io = require('socket.io')(http);

expressHandlebars = require('express-handlebars');

mongoose = require('mongoose');

bodyParser = require('body-parser');

app.use(bodyParser.urlencoded({
  extended: true
}));

app.use(express["static"](__dirname + '/public'));

app.engine('handlebars', expressHandlebars({
  defaultLayout: 'main'
}));

app.set('view engine', 'handlebars');

mongoose.connect('mongodb://localhost:27017/crew_db');

db = mongoose.connection;

db.on('error', console.error.bind(console, 'connection error:'));

db.once('open', function(callback) {});

messageSchema = mongoose.Schema({
  created: Date,
  content: String,
  username: String,
  group: String
});

Chat = mongoose.model('Chat', messageSchema);

app.get('/', function(req, res) {
  return res.render('home');
});

app.get('/:group', function(req, res) {
  return Chat.find({
    'group': req.params.group
  }).exec(function(err, msgs) {
    var group;
    console.log(msgs);
    group = req.params.group;
    return res.render('group', {
      msgs: msgs,
      group: group
    });
  });
});

app.post('/:group/msg', function(req, res) {
  var chat, msg;
  msg = {
    created: new Date(),
    content: req.body.message,
    username: 'camlinke',
    group: req.params.group
  };
  chat = new Chat(msg);
  chat.save(function(err, savedChat) {
    return console.log(savedChat);
  });
  return res.send('created');
});

io.on('connection', function(socket) {
  console.log('a user connected');
  socket.on('chat message', function(msg) {
    console.log("message: " + msg);
    return io.emit('chat message', msg);
  });
  return socket.on('disconnect', function() {
    return console.log('user disconnected');
  });
});

server = http.listen('4000', function() {
  var host, port;
  host = server.address().address;
  port = server.address().port;
  console.log("Example app listening at http://" + host + ":" + port);
});
