// Generated by CoffeeScript 1.7.1
app.get('/group/:group', function(req, res) {
  return Chat.find({
    'group': req.params.group
  }).exec(function(err, msgs) {
    var foo, group, username;
    if (!req.session.username) {
      foo = "bar";
      req.session.group = req.params.group;
      return res.redirect('/users/create');
    } else {
      group = req.params.group;
      username = req.session.username;
      req.session.group = group;
      return res.render('group', {
        msgs: msgs,
        group: group,
        username: username
      });
    }
  });
});

app.post('/createGroup', function(req, res) {
  return Chat.find({
    'group': req.body.groupName
  }).exec(function(err, group) {
    var error, g;
    if (group.length > 0) {
      error = "group already exists";
      console.log(error);
      return res.redirect("/");
    } else {
      g = {
        created: +(new Date),
        endDate: +(new Date) + 86400000,
        groupName: req.body.groupName,
        password: ""
      };
      group = new Group(g);
      return group.save(function(err, savedGroup) {
        return res.redirect("/group/" + req.body.groupName);
      });
    }
  });
});

module.exports = router;
