// Generated by CoffeeScript 1.7.1
var express, router;

express = require('express');

router = express.Router();

app.get('/users/create', function(req, res) {
  return res.render('username');
});

app.post('/users/create', function(req, res) {
  req.session.username = req.body.username;
  return res.redirect("/groups/" + req.session.group);
});

module.exports = router;
