// Generated by CoffeeScript 1.7.1
var groupSchema, mongoose;

mongoose = require('mongoose');

groupSchema = mongoose.Schema({
  created: Date,
  endDate: Date,
  groupName: String,
  password: String
});

module.exports = mongoose.model('Group', groupSchema);
